export const types = {
    uiOpenNoteModal: '[ui] Open note modal',
    uiOpenRoutineModal: '[ui] Open routine modal',
    uiOpenListModal: '[ui] Open list modal',
    uiOpenUserEditModal: '[ui] Open user edit modal',
    uiCloseModal: '[ui] Close modal',
    uiOpenSidebar: '[ui] Open sidebar',
    uiCloseSidebar: '[ui] Close sidebar',
    uiSetError: '[ui] Set Error',
    uiSetBackgroundImage: '[ui] Set background image',

    routineLoaded: '[routine] Loaded routine',
    routineAddNew: '[routine] Add new routine',
    routineDelete: '[routine] Delete routine',
    routineUpdate: '[routine] Update routine',
    routineSetActive: '[routine] Set active',
    routineClearActive: '[routine] Clear Active',
    routineClear: '[routine] Clear',

    noteSetActive: '[note] Set Active',
    noteClearActive: '[note] Clear Active',
    noteLoaded: '[note] Loaded notes',
    noteAddNew: '[note] Add new note',
    noteUpdate: '[note] Update note',
    noteClear: '[note] Clear notes',
    noteDelete: '[note] Delete note',

    taskLoaded: '[task] Loaded days',
    taskUpdate: '[task] Update tasks',
    taskClear: '[task] Clear tasks',
    taskClearChanges: '[task] Clear Changes',
    taskAddChange: '[task] Add Change',
    taskUpdateChange: '[task] Update Change',
    taskAddNewDay: '[task] Add new Day',

    listLoaded: '[list] Loaded lists',
    listSetActive: '[list] Set Active',
    listSetActiveRow: '[list] Active row',
    listClearActive: '[list] Clear Active',
    listAddNewList: '[list] Add new list',
    listAddNewRow: '[list] Add new row',
    listDelete: '[list] Delete list',
    listDeleteRow: '[list] Delete row',
    listUpdate: '[list] Update list',
    listUpdateRow: '[list] Update row',

    authCheckingFinish: '[auth] Finish checking login state',
    authLogin: '[auth] Login',
    authStartLogin: '[auth] Start Login',
    authStartRegister: '[auth] Start register',
    authStartTokenRenew: '[auth] Start token renew',
    authLogout: '[auth] Logout',
}